### ISSUE TITLE
Filter by name does not work on source.rcsb.org

### ISSUE THREAD

**Issue by andreasprlic** [rcsb/symmetry#32]
Filter by scop name does not work. This is the exception that I get

java.lang.NoSuchMethodException: org.biojava3.structure.align.symm.census2.SimpleResult.getName()
        at java.lang.Class.getMethod(Class.java:1665)
        at org.rcsb.fatcat.server.symmetry.CensusResultFilter.filterOrderIndependentParam(CensusResultFilter.java:182)
        at org.rcsb.fatcat.server.symmetry.CensusResultFilter.getSearchCondition(CensusResultFilter.java:148)
        at org.rcsb.fatcat.server.symmetry.CensusResultFilter.filter(CensusResultFilter.java:72)
        at org.apache.jsp.censusXMLData_jsp._jspService(censusXMLData_jsp.java:117)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

**Comment by lafita** [comment]
Should we close that?

**Comment by lafita** [comment]
If the issue was regarding the census table in [source.rcsb.org](http://source.rcsb.org/jfatcatserver/scopResults.jsp), neither filter by **SCOP name** nor filter by **SCOP superfamily** work. It is not a problem with String comparison, because the option filter by **SCOP description** works as expected. Filter by **Unit** doesn't work neither.
