### ISSUE TITLE
NPE with RC3

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#92]
```
$ cesymm-2.0.0-RC3/runCESymm.sh --symmlevels 3 --order 8 d1flgb1
Structure	NumRepeats	SymmGroup	Reason
18542 [pool-2-thread-1] ERROR workers.CeSymmWorker - Could not complete job: d1flgb1
java.lang.NullPointerException
	at org.biojava.nbio.structure.symmetry.internal.CeSymmResult.isSignificant(CeSymmResult.java:84) ~[cesymm-2.0.0-RC3.jar:2.0.0-SNAPSHOT]
	at org.biojava.nbio.structure.symmetry.internal.CeSymmIterative.iterate(CeSymmIterative.java:147) ~[cesymm-2.0.0-RC3.jar:2.0.0-SNAPSHOT]
	at org.biojava.nbio.structure.symmetry.internal.CeSymmIterative.execute(CeSymmIterative.java:110) ~[cesymm-2.0.0-RC3.jar:2.0.0-SNAPSHOT]
	at org.biojava.nbio.structure.symmetry.internal.CeSymm.analyze(CeSymm.java:387) ~[cesymm-2.0.0-RC3.jar:2.0.0-SNAPSHOT]
	at workers.CeSymmWorker.run(CeSymmWorker.java:68) [cesymm-2.0.0-RC3.jar:2.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by sbliven** [comment]
Will be fixed in Biojava 4.2.12
